# Generated by Django 5.2.6 on 2025-12-04 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=25, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('purchase_date', models.DateField()),
                ('store_location', models.CharField(max_length=100)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='unit_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registered Unit',
                'verbose_name_plural': 'Registered Units',
                'ordering': ['-created_at'],
            },
        ),
    ]
