# Generated by Django 5.2.6 on 2025-12-07 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
                ('has_serviced_before', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='unit.registerunit')),
            ],
            options={
                'verbose_name': 'Service Schedule',
                'verbose_name_plural': 'Service Schedules',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
