# Generated by Django 5.2.6 on 2025-12-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0003_sellunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerunit',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
