# Generated by Django 5.2.6 on 2025-12-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0004_registerunit_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleservice',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
