# Generated by Django 5.2.6 on 2025-12-14 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='chat/attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'image')], max_length=10, null=True),
        ),
    ]
